In [7]:
import torch

# Assuming these variables are defined: N_H, TDST_BQ, MASK_K_BK
# Example values for demonstration (You should replace them with your actual values)
N_H = 40  # Example: Number of heads
TDST_BQ = 128  # Example: TDST divided by block size for query
MASK_K_BK = 256  # Example: MASK_K divided by block size for keys

# Initialize the tensors with example shapes
# Replace these with your actual tensors
indices = torch.zeros(N_H, TDST_BQ, MASK_K_BK, dtype=torch.long)
ks = torch.randint(low=0, high=MASK_K_BK, size=(N_H, TDST_BQ), dtype=torch.long)  # Random values as an example


In [8]:
range_tensor = torch.arange(MASK_K_BK, device=indices.device).expand_as(indices)

In [10]:
print(range_tensor)


tensor([[[  0,   1,   2,  ..., 253, 254, 255],
         [  0,   1,   2,  ..., 253, 254, 255],
         [  0,   1,   2,  ..., 253, 254, 255],
         ...,
         [  0,   1,   2,  ..., 253, 254, 255],
         [  0,   1,   2,  ..., 253, 254, 255],
         [  0,   1,   2,  ..., 253, 254, 255]],

        [[  0,   1,   2,  ..., 253, 254, 255],
         [  0,   1,   2,  ..., 253, 254, 255],
         [  0,   1,   2,  ..., 253, 254, 255],
         ...,
         [  0,   1,   2,  ..., 253, 254, 255],
         [  0,   1,   2,  ..., 253, 254, 255],
         [  0,   1,   2,  ..., 253, 254, 255]],

        [[  0,   1,   2,  ..., 253, 254, 255],
         [  0,   1,   2,  ..., 253, 254, 255],
         [  0,   1,   2,  ..., 253, 254, 255],
         ...,
         [  0,   1,   2,  ..., 253, 254, 255],
         [  0,   1,   2,  ..., 253, 254, 255],
         [  0,   1,   2,  ..., 253, 254, 255]],

        ...,

        [[  0,   1,   2,  ..., 253, 254, 255],
         [  0,   1,   2,  ..., 253, 254, 255]

In [11]:
print(indices.shape)
print(ks)

torch.Size([40, 128, 256])
tensor([[189, 184, 210,  ..., 217, 246,  64],
        [219, 171,  46,  ...,  49, 129, 150],
        [113, 142, 175,  ...,  84,  71,  56],
        ...,
        [123,  17, 202,  ...,  16,  50, 117],
        [119,  49,  44,  ...,  79, 151,  47],
        [ 89, 195,  77,  ...,  81,  28, 109]])


In [19]:
mask = range_tensor >= ks.unsqueeze(-1)
print(ks.unsqueeze(-1).shape)
print(ks.unsqueeze(-1))

print(mask)
print(mask.shape)

torch.Size([40, 128, 1])
tensor([[[189],
         [184],
         [210],
         ...,
         [217],
         [246],
         [ 64]],

        [[219],
         [171],
         [ 46],
         ...,
         [ 49],
         [129],
         [150]],

        [[113],
         [142],
         [175],
         ...,
         [ 84],
         [ 71],
         [ 56]],

        ...,

        [[123],
         [ 17],
         [202],
         ...,
         [ 16],
         [ 50],
         [117]],

        [[119],
         [ 49],
         [ 44],
         ...,
         [ 79],
         [151],
         [ 47]],

        [[ 89],
         [195],
         [ 77],
         ...,
         [ 81],
         [ 28],
         [109]]])
tensor([[[False, False, False,  ...,  True,  True,  True],
         [False, False, False,  ...,  True,  True,  True],
         [False, False, False,  ...,  True,  True,  True],
         ...,
         [False, False, False,  ...,  True,  True,  True],
         [False, False, False,  ...,  T

In [20]:
indices

tensor([[[0, 0, 0,  ..., 0, 0, 0],
         [0, 0, 0,  ..., 0, 0, 0],
         [0, 0, 0,  ..., 0, 0, 0],
         ...,
         [0, 0, 0,  ..., 0, 0, 0],
         [0, 0, 0,  ..., 0, 0, 0],
         [0, 0, 0,  ..., 0, 0, 0]],

        [[0, 0, 0,  ..., 0, 0, 0],
         [0, 0, 0,  ..., 0, 0, 0],
         [0, 0, 0,  ..., 0, 0, 0],
         ...,
         [0, 0, 0,  ..., 0, 0, 0],
         [0, 0, 0,  ..., 0, 0, 0],
         [0, 0, 0,  ..., 0, 0, 0]],

        [[0, 0, 0,  ..., 0, 0, 0],
         [0, 0, 0,  ..., 0, 0, 0],
         [0, 0, 0,  ..., 0, 0, 0],
         ...,
         [0, 0, 0,  ..., 0, 0, 0],
         [0, 0, 0,  ..., 0, 0, 0],
         [0, 0, 0,  ..., 0, 0, 0]],

        ...,

        [[0, 0, 0,  ..., 0, 0, 0],
         [0, 0, 0,  ..., 0, 0, 0],
         [0, 0, 0,  ..., 0, 0, 0],
         ...,
         [0, 0, 0,  ..., 0, 0, 0],
         [0, 0, 0,  ..., 0, 0, 0],
         [0, 0, 0,  ..., 0, 0, 0]],

        [[0, 0, 0,  ..., 0, 0, 0],
         [0, 0, 0,  ..., 0, 0, 0],
         [0,

In [22]:
indices[mask] = 32000
print(indices)

tensor([[[    0,     0,     0,  ..., 32000, 32000, 32000],
         [    0,     0,     0,  ..., 32000, 32000, 32000],
         [    0,     0,     0,  ..., 32000, 32000, 32000],
         ...,
         [    0,     0,     0,  ..., 32000, 32000, 32000],
         [    0,     0,     0,  ..., 32000, 32000, 32000],
         [    0,     0,     0,  ..., 32000, 32000, 32000]],

        [[    0,     0,     0,  ..., 32000, 32000, 32000],
         [    0,     0,     0,  ..., 32000, 32000, 32000],
         [    0,     0,     0,  ..., 32000, 32000, 32000],
         ...,
         [    0,     0,     0,  ..., 32000, 32000, 32000],
         [    0,     0,     0,  ..., 32000, 32000, 32000],
         [    0,     0,     0,  ..., 32000, 32000, 32000]],

        [[    0,     0,     0,  ..., 32000, 32000, 32000],
         [    0,     0,     0,  ..., 32000, 32000, 32000],
         [    0,     0,     0,  ..., 32000, 32000, 32000],
         ...,
         [    0,     0,     0,  ..., 32000, 32000, 32000],
         [

In [24]:
import torch

# Assuming ks is your tensor with shape (N_H, TDST_BQ)
# Example tensor for demonstration purposes (replace with your tensor)
N_H = 2
TDST_BQ = 5
ks = torch.randint(low=0, high=20, size=(N_H, TDST_BQ))
print(ks)
# To find the maximum value across the entire tensor
max_value = ks.max().item()

print(f"The maximum value in ks is: {max_value}")


tensor([[14,  7,  4, 18, 19],
        [11, 18,  9, 10,  5]])
The maximum value in ks is: 19
